{% set name = "pcdscalc" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 49d10eea4ec49376fb222c7b435b8178f118ba281ce4ade16f7f99f114215eaa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - numpy
    - xraydb

test:
  imports:
    - pcdscalc

about:
  home: https://github.com/pcdshub/pcdscalc
  doc_url: https://pcdshub.github.io/pcdscalc
  dev_url: https://github.com/pcdshub/pcdscalc
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE
  summary: Control system-agnostic scientific calculation routines

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
    - klauer
    - tangkong
    - zllentz
