{% set name = "pcdscalc" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 135af1c33f08ca451835f5cd27cdbf595f71e1ca53b91f05feff2c41bd357fbc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - xraydb

test:
  imports:
    - pcdscalc

about:
  home: https://github.com/pcdshub/pcdscalc
  doc_url: https://pcdshub.github.io/pcdscalc
  dev_url: https://github.com/pcdshub/pcdscalc
  license: SLAC Open
  license_family: Other
  license_file: LICENSE
  summary: Control system-agnostic scientific calculation routines

extra:
  recipe-maintainers:
    - klauer
    - zllentz
    - zrylettc
