{% set name = "pcdscalc" %}
{% set version = "0.6.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: cfd11048e43dea51d0851ec8f283e4fddcc7934f65c3e0173dfd29a086e90575

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy <2.0
    - ophyd
    - periodictable
    - scipy
    - xraydb
    - xraylib

test:
  requires:
    - python {{ python_min }}
  imports:
    - pcdscalc

about:
  home: https://github.com/pcdshub/pcdscalc
  doc_url: https://pcdshub.github.io/pcdscalc
  dev_url: https://github.com/pcdshub/pcdscalc
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE
  summary: Control system-agnostic scientific calculation routines

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
